#!/bin/bash

#SBATCH --job-name=test #Assign a descriptive job name

#SBATCH -N 1                    # Request 1 node
#SBATCH --mem=100G               # Request 400GB memory
#SBATCH -t 5:50:00             # Set maximum time


#SBATCH --gres=gpu:1
##SBATCH --gres=gpu:nvidia_a100_80:1
##SBATCH --partition=tier2_gpu_dev
#SBATCH --partition=tier2_gpu
#SBATCH --account=aristeidis_sotiras
#SBATCH --exclude=gpu02

#SBATCH --output=slurm-%A_%a.out
#SBATCH --error=slurm-%A_%a.err

source /home/l.peiwang/miniconda3/etc/profile.d/conda.sh

conda activate myenv



#module load cuda/11.8
#module load cudnn/8.1.1


data:
  train: /scratch/l.peiwang/cd_dataset.h5
  validation: /scratch/l.peiwang/cd_dataset.h5
  test: /scratch/l.peiwang/cd_dataset.h5

output:
  path: /scratch/l.peiwang/results/

python train_mri2pet.py --data_dir /scratch/l.peiwang/ --results_folder /scratch/l.peiwang/results/
python train_mri2pet.py --data_dir /scratch/l.peiwang/ --results_folder /scratch/l.peiwang/results/ --eval_mode True --synthesis True
